config/routes.rb
ArcheryMongodbExample::Application.routes.draw do
  resources :events

  resources :rounds do
    resources :events
  end

  resources :archers

   root 'welcome#index'

end

app/models/archer.rb
class Archer
  include Mongoid::Document
  field :name, type: String
end

app/models/event.rb
class Event
  include Mongoid::Document
  field :name, type: String
  field :event_date, type: Date
  field :type, type: String
  embeds_many :rounds
end

app/models/round.rb
class Round
  include Mongoid::Document
  field :name, type: String
  field :face, type: String
  field :distance, type: Integer
  field :total_arrows, type: Integer
  field :scores, type: Array
  embedded_in :event
  belongs_to :archer

  attr_accessor :event_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/archers_controller.rb
class ArchersController < ApplicationController
  before_action :set_archer, only: [:show, :edit, :update, :destroy]

  # GET /archers
  # GET /archers.json
  def index
    @archers = Archer.all
  end

  # GET /archers/1
  # GET /archers/1.json
  def show
    @id = BSON::ObjectId.from_string(params[:id])
    @events = Event.where('rounds.archer_id' => @id).all

    @map = %Q{function(){
      for (var idx = 0; idx < this.rounds.length; idx++) {
        var key = this.rounds[idx].archer_id;
        var value = this.rounds[idx].scores;
        emit(key, value);
      }
    }}

    @reduce = %Q{function(key_archer_id, values){
      var total = 0;
      reducedVal = { score: 0};
      for (var idx = 0; idx < values.length; idx++) {
          scores = values[idx];
          for (var j = 0; j < scores.length; j++) {
            reducedVal.score += parseInt(scores[j]);
          }
      }
      return reducedVal;
    }}

    Event.map_reduce(@map, @reduce).out(inline: 1).each do |doc|
      @total_score = doc["value"]["score"] if doc['_id'] == @id
    end
  end

  # GET /archers/new
  def new
    @archer = Archer.new
  end

  # GET /archers/1/edit
  def edit
  end

  # POST /archers
  # POST /archers.json
  def create
    @archer = Archer.new(archer_params)

    respond_to do |format|
      if @archer.save
        format.html { redirect_to @archer, notice: 'Archer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @archer }
      else
        format.html { render action: 'new' }
        format.json { render json: @archer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archers/1
  # PATCH/PUT /archers/1.json
  def update
    respond_to do |format|
      if @archer.update(archer_params)
        format.html { redirect_to @archer, notice: 'Archer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @archer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archers/1
  # DELETE /archers/1.json
  def destroy
    @archer.destroy
    respond_to do |format|
      format.html { redirect_to archers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archer
      @archer = Archer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archer_params
      params.require(:archer).permit(:name)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show

  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params.merge({:event_date => params[:event]["event_date(3i)"] + "-" + params[:event]["event_date(2i)"] + params[:event]["event_date(1i)"]}))
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :type)
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @event = Event.find(params[:round][:event_id])
    respond_to do |format|
      if @event.rounds.create(round_params.merge({:scores => round_params[:scores].split(",")}))
        format.html { redirect_to events_url, notice: 'Round was successfully created.' }
        format.json { render action: 'show', status: :created, location: @round }
      else
        format.html { render action: 'new' }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:name, :face, :distance, :total_arrows, :scores, :archer_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archers_helper.rb
module ArchersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/archers/_form.html.erb
<%= form_for(@archer) do |f| %>
  <% if @archer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archer.errors.count, "error") %> prohibited this archer from being saved:</h2>

      <ul>
      <% @archer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archers/edit.html.erb
<h1>Editing archer</h1>

<%= render 'form' %>

<%= link_to 'Show', @archer %> |
<%= link_to 'Back', archers_path %>

app/views/archers/index.html.erb
<h1>Listing archers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @archers.each do |archer| %>
      <tr>
        <td><%= archer.name %></td>
        <td><%= link_to 'Show', archer %></td>
        <td><%= link_to 'Edit', edit_archer_path(archer) %></td>
        <td><%= link_to 'Destroy', archer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archer', new_archer_path %>

app/views/archers/new.html.erb
<h1>New archer</h1>

<%= render 'form' %>

<%= link_to 'Back', archers_path %>

app/views/archers/show.html.erb
<p id="notice"><%= notice %></p>
<br/>
<p>
  <h1>Archer Name: <%= @archer.name %></h1>
</p>

<p>
  <h2>Total Score till date: <%= @total_score %></h2>
</p>

<br/>
<h3>Events participated in:</h3>
<hr/>

<% @events.each do |event| %>
<p>
  <strong>Event Name:</strong>
  <%= event.name %>
</p>

<p>
  <strong>Event Date:</strong>
  <%= event.event_date %>
</p>

<p>
  <strong>Event Type:</strong>
  <%= event.type %>
</p>

<p>
  <strong>Rounds:</strong>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Face</th>
    <th>Distance</th>
    <th>Total arrows</th>
    <th>Scores</th>
    <th>Archer Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% event.rounds.each do |round| %>
      <tr>
        <td><%= round.name %></td>
        <td><%= round.face %></td>
        <td><%= round.distance %></td>
        <td><%= round.total_arrows %></td>
        <td><%= round.scores %></td>
        <td><%= round.archer.name %></td>
      </tr>
  <% end %>
  </tbody>
</table>

</p>
<hr/>
<%end%>
<%= link_to 'Edit', edit_archer_path(@archer) %> |
<%= link_to 'Back', archers_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.event_date %></td>
        <td><%= event.type %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %><br/>
<%= link_to 'New Round', new_round_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Type:</strong>
  <%= @event.type %>
</p>

<p>
  <strong>Rounds:</strong>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Face</th>
    <th>Distance</th>
    <th>Total arrows</th>
    <th>Scores</th>
    <th>Archer Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @event.rounds.each do |round| %>
      <tr>
        <td><%= round.name %></td>
        <td><%= round.face %></td>
        <td><%= round.distance %></td>
        <td><%= round.total_arrows %></td>
        <td><%= round.scores %></td>
        <td><%= round.archer.name %></td>
        <td><%= link_to 'Edit', edit_round_path(round) %></td>
        <td><%= link_to 'Destroy', round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArcheryMongodbExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rounds/_form.html.erb
<%= form_for(@round) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :face %><br>
    <%= f.text_field :face %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.number_field :distance %>
  </div>
  <div class="field">
    <%= f.label :total_arrows %><br>
    <%= f.number_field :total_arrows %>
  </div>
  <div class="field">
    <%= f.label :scores %><br>
    <%= f.text_field :scores %>
  </div>
  <div class="field">
      <%= f.label :archer_id %><br>
      <%= f.collection_select :archer_id, Archer.all, :id, :name %>
  </div>
  <div class="field">
      <%= f.label :event_id %><br>
      <%= f.collection_select :event_id, Event.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing round</h1>

<%= render 'form' %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<h1>Listing rounds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Face</th>
      <th>Distance</th>
      <th>Total arrows</th>
      <th>Scores</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= round.name %></td>
        <td><%= round.face %></td>
        <td><%= round.distance %></td>
        <td><%= round.total_arrows %></td>
        <td><%= round.scores %></td>
        <td><%= link_to 'Show', round %></td>
        <td><%= link_to 'Edit', edit_round_path(round) %></td>
        <td><%= link_to 'Destroy', round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_round_path %>

app/views/rounds/new.html.erb
<h1>New round</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @round.name %>
</p>

<p>
  <strong>Face:</strong>
  <%= @round.face %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @round.distance %>
</p>

<p>
  <strong>Total arrows:</strong>
  <%= @round.total_arrows %>
</p>

<p>
  <strong>Scores:</strong>
  <%= @round.scores %>
</p>

<%= link_to 'Edit', edit_round_path(@round) %> |
<%= link_to 'Back', rounds_path %>

app/views/welcome/index.html.erb
<h1>Archery Application</h1>
<h2>Demonstrating a basic archery use case with Ruby on Rails and MongoDB</h2>
<br/>
<%= link_to 'Archers', archers_path %><br/>
<%= link_to 'Events', events_path %><br/>